SELECT
    CONCAT(LEFT(NU_INSCRICAO, LEN(NU_INSCRICAO) - 4), '****') AS NUM_INSCRICAO,
	Q006 AS CAT_RENDA,
    R.FAIXA AS FAIXA,
	TP_DEPENDENCIA_ADM_ESC,
    NU_NOTA_MT AS MAIORES_NOTAS,
	NO_MUNICIPIO_ESC,
	SG_UF_ESC AS ESTADO,
	I.IDHM_E AS IDH_EDUC
INTO ALUNOS_NOTA_MAX
FROM MICRODADOS_ENEM_2022 M
INNER JOIN dbo.renda_enem R ON M.Q006 = R.CATEGORIA
INNER JOIN dbo.IDH I ON CONCAT(M.NO_MUNICIPIO_ESC, ' (', M.SG_UF_ESC, ')') = I.MUNICIPIO
WHERE NU_NOTA_MT = (
    SELECT MAX(NU_NOTA_MT) AS maior_nota
    FROM MICRODADOS_ENEM_2022
)
AND NO_MUNICIPIO_ESC <> ' '
ORDER BY CAT_RENDA, IDH_EDUC;

WITH CTE AS (
    SELECT
        COUNT(TP_DEPENDENCIA_ADM_ESC) AS QUANTIDADE,
        TP_DEPENDENCIA_ADM_ESC,
        CASE
			WHEN TP_DEPENDENCIA_ADM_ESC = '1' THEN 'FEDERAL'
			WHEN TP_DEPENDENCIA_ADM_ESC = '2' THEN 'ESTADUAL'
			WHEN TP_DEPENDENCIA_ADM_ESC = '3' THEN 'MUNICIPAL'
            WHEN TP_DEPENDENCIA_ADM_ESC = '4' THEN 'PARTICULAR'
        END AS TIPO_ESCOLA
    FROM MICRODADOS_ENEM_2022
    WHERE NU_NOTA_MT = (
        SELECT MAX(NU_NOTA_MT) AS maior_nota
        FROM MICRODADOS_ENEM_2022
    )
    AND TP_DEPENDENCIA_ADM_ESC <> ' '
    GROUP BY TP_DEPENDENCIA_ADM_ESC
)

SELECT
    QUANTIDADE,
    TP_DEPENDENCIA_ADM_ESC,
    TIPO_ESCOLA,
    CAST((QUANTIDADE * 100.0 / SUM(QUANTIDADE) OVER ()) AS DECIMAL(18, 2)) AS PERCENTUAL
INTO ANALISE_NOTA_MAX
FROM CTE
ORDER BY QUANTIDADE DESC;